INSERT INTO alunos (nome) VALUES ('Ana Silva');
INSERT INTO alunos (nome) VALUES ('Bruno Souza');
INSERT INTO alunos (nome) VALUES ('Carol Beuting');
INSERT INTO alunos (nome) VALUES ('Carla Mendes');
INSERT INTO alunos (nome) VALUES ('Diego Lima');
INSERT INTO alunos (nome) VALUES ('Eduarda Costa');
INSERT INTO alunos (nome) VALUES ('Felipe Rocha');
INSERT INTO alunos (nome) VALUES ('Gabriela Alves');
INSERT INTO alunos (nome) VALUES ('Henrique Dias');
INSERT INTO alunos (nome) VALUES ('Isabela Martins');
INSERT INTO alunos (nome) VALUES ('João Pereira');
INSERT INTO alunos (nome) VALUES ('Katsuki Kirishima');
INSERT INTO alunos (nome) VALUES ('Laura Gonçalves');
INSERT INTO alunos (nome) VALUES ('Nananzoka dos Santos');
INSERT INTO alunos (nome) VALUES ('Nicole Nasato');
INSERT INTO alunos (nome) VALUES ('Mitski');