INSERT INTO professores (nome) VALUES ('Aghata Nunes');
INSERT INTO professores (nome) VALUES ('Aizawa Shouta');
INSERT INTO professores (nome) VALUES ('Alanzoka The Gamer');
INSERT INTO professores (nome) VALUES ('All Might');
INSERT INTO professores (nome) VALUES ('Bruno Berti');
INSERT INTO professores (nome) VALUES ('Eijirou Bakugou');
INSERT INTO professores (nome) VALUES ('Felipe Neto');
INSERT INTO professores (nome) VALUES ('Henry Danger');
INSERT INTO professores (nome) VALUES ('Izuku Midoriya');
INSERT INTO professores (nome) VALUES ('Mamonas Assassinas');
INSERT INTO professores (nome) VALUES ('Max Thunderman');
INSERT INTO professores (nome) VALUES ('Midnight');
INSERT INTO professores (nome) VALUES ('Mirko');
INSERT INTO professores (nome) VALUES ('Mount Gameplays');
INSERT INTO professores (nome) VALUES ('Present Mic');
INSERT INTO professores (nome) VALUES ('Reigen Arataka');
INSERT INTO professores (nome) VALUES ('Seu Zezinho');
INSERT INTO professores (nome) VALUES ('Time Turner');
INSERT INTO professores (nome) VALUES ('Vanessa Wolf');
INSERT INTO professores (nome) VALUES ('Ygona');